version: '3.8'

services:
  # PostgreSQL 데이터베이스 (프로덕션)
  db:
    image: postgres:15-alpine
    container_name: myzone_db_prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - myzone_network_prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  # Redis 캐시 (프로덕션)
  redis:
    image: redis:7-alpine
    container_name: myzone_redis_prod
    volumes:
      - redis_data_prod:/data
    networks:
      - myzone_network_prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  # FastAPI 백엔드 (프로덕션)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: myzone_backend_prod
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DEBUG=false
      - ENVIRONMENT=production
      - LOG_LEVEL=${LOG_LEVEL}
      - SMS_API_KEY=${SMS_API_KEY}
      - PAYMENT_API_KEY=${PAYMENT_API_KEY}
      - EMAIL_API_KEY=${EMAIL_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
    volumes:
      - backend_uploads_prod:/app/uploads
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - myzone_network_prod
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  # React 프론트엔드 (프로덕션)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: myzone_frontend_prod
    depends_on:
      - backend
    networks:
      - myzone_network_prod
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    container_name: myzone_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - myzone_network_prod
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  # 백업 서비스
  backup:
    image: postgres:15-alpine
    container_name: myzone_backup
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./backups:/backups
      - ./scripts/backup.sh:/backup.sh
    depends_on:
      - db
    networks:
      - myzone_network_prod
    restart: "no"
    entrypoint: ["sh", "/backup.sh"]

volumes:
  postgres_data_prod:
  redis_data_prod:
  backend_uploads_prod:

networks:
  myzone_network_prod:
    driver: bridge