# 프로덕션 환경 설정
name: production
description: MyZone 프로덕션 환경
protection_rules:
  - type: required_reviewers
    required_reviewers: 2
  - type: wait_timer
    wait_timer: 300  # 5분 대기
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: false