# 스테이징 환경 설정
name: staging
description: MyZone 스테이징 환경
protection_rules:
  - type: required_reviewers
    required_reviewers: 1
  - type: wait_timer
    wait_timer: 0
deployment_branch_policy:
  protected_branches: false
  custom_branch_policies: true
  custom_branches:
    - develop