"""add admin activity logs

Revision ID: 007
Revises: 006
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '007'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_activity_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=False, comment='관리자 ID'),
        sa.Column('action', sa.String(length=100), nullable=False, comment='수행한 작업'),
        sa.Column('resource_type', sa.String(length=50), nullable=True, comment='대상 리소스 타입 (order, user, admin 등)'),
        sa.Column('resource_id', sa.Integer(), nullable=True, comment='대상 리소스 ID'),
        sa.Column('method', sa.String(length=10), nullable=True, comment='HTTP 메소드'),
        sa.Column('endpoint', sa.String(length=255), nullable=True, comment='API 엔드포인트'),
        sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP 주소'),
        sa.Column('user_agent', sa.Text(), nullable=True, comment='User Agent'),
        sa.Column('description', sa.Text(), nullable=True, comment='활동 설명'),
        sa.Column('request_data', sa.JSON(), nullable=True, comment='요청 데이터'),
        sa.Column('response_status', sa.Integer(), nullable=True, comment='응답 상태 코드'),
        sa.Column('success', sa.String(length=10), nullable=False, comment='성공 여부'),
        sa.Column('error_message', sa.Text(), nullable=True, comment='오류 메시지'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_activity_logs_admin_id'), 'admin_activity_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_activity_logs_created_at'), 'admin_activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_activity_logs_action'), 'admin_activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_activity_logs_resource_type'), 'admin_activity_logs', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_activity_logs_resource_type'), table_name='admin_activity_logs')
    op.drop_index(op.f('ix_admin_activity_logs_action'), table_name='admin_activity_logs')
    op.drop_index(op.f('ix_admin_activity_logs_created_at'), table_name='admin_activity_logs')
    op.drop_index(op.f('ix_admin_activity_logs_admin_id'), table_name='admin_activity_logs')
    op.drop_table('admin_activity_logs')
    # ### end Alembic commands ###